#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    01 - List Network interfaces                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/02 17:53:34 by abarthel          #+#    #+#              #
#    Updated: 2019/01/02 17:53:34 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Get && list network interfaces
	echo "\033[92mList of Network Interfaces: \033[0m"
	ifconfig -l | tr " " "\n"

# List with more details
#	echo "\033[92mList of Network Interfaces: \033[0m"
#	networksetup -listallhardwareports
