#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    02 Ethernet broadcast add and network              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/03 10:34:02 by abarthel          #+#    #+#              #
#    Updated: 2019/01/03 10:34:02 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Get info about the ethernet inferface
ifconfig en0

# Get broadcast address && IP addresses belonging to the same network
# IPv4 boradcast address example 11.10.255.255
#ifconfig en0 | grep -o -e "[0-9]*.[0-9]*.255.255"

# Set number of packets for ping
NB=2
read -p "Press [enter] to look at Network interface Addresses..."
# MacOS IPv4 -> ping all interfaces on broadcast adress -> list network addresses
ifconfig en0 | grep -o -e "[0-9]*.[0-9]*.255.255" | xargs ping -c $NB >/dev/null
arp -a | grep -v "?" | grep -o -e "[0-9]*[.][0-9]*[.][0-9]*[.][0-9]*"

#if [[ $ARP_OUTPUT =~ $MASK ]]; then
#	echo $ARP_OUTPUT
#  fi

