#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    03 Wifi Mac Address                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/03 12:46:50 by abarthel          #+#    #+#              #
#    Updated: 2019/01/03 12:46:50 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Test WIFI settings to recognize WIFI network interface
#	sudo ifconfig <interface> down
#	sudo ifconfig <interface> up

# Get WIFI mac address
	echo "\033[92mWIFI Mac Address: \033[0m"
	ifconfig en1 | grep -o -e "..:..:..:..:..:.."

