#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    04 Identify default gateway in rooting table       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/03 10:34:02 by abarthel          #+#    #+#              #
#    Updated: 2019/01/03 10:34:02 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Identify default gateway using rooting table
	echo "\033[92mDefault Gateway Address: \033[0m"
	netstat -rn | grep -e "default" | grep -o -e "[0-9]*[.][0-9]*[.][0-9]*[.][0-9]*"
#	route get default | grep -e "gateway" | xargs echo | cut -d " " -f2


# https://www.freebsd.org/doc/handbook/network-routing.html
