#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    04 Identify default gateway in rooting table       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/03 10:34:02 by abarthel          #+#    #+#              #
#    Updated: 2019/01/03 10:34:02 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# https://www.freebsd.org/doc/handbook/network-routing.html

# Identify default gateway using rooting table
	netstat -r
	
