#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    05 Get DNS IP                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/07 13:11:49 by abarthel          #+#    #+#              #
#    Updated: 2019/01/07 13:11:49 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Set website
	WWW="slash16.org"

# Get WWW DNS IP using dig
	echo "\033[92m$WWW DNS IP: \033[0m"
	dig $WWW | grep -e "SERVER" | grep -o -e "[0-9]*[.][0-9]*[.][0-9]*[.][0-9]*" | head -1

# Get WWW DNS IP using nslookup
#	echo "\033[92m$WWW DNS IP using nslookup: \033[0m"
#	nslookup slash16.org | grep -e "Server" | cut -d ":" -f2 | xargs echo
