#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    10 Traceroute - get network interfaces IP          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/08 14:12:39 by abarthel          #+#    #+#              #
#    Updated: 2019/01/08 14:12:39 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Set the target
	WWW="slash16.org"

# Get the IP address of WWW using public DNS query
	IP_ADD=$(nslookup slash16.fr 8.8.8.8 | sed -n /'answer'/,//p | grep -e "Address" | grep -o -e "[0-9]*[.][0-9]*[.][0-9]*[.][0-9]*")

# Trace route (identify network interfaces packets are passing through)
	traceroute $IP_ADD
