#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    10 Traceroute - get network interfaces IP          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/08 14:12:39 by abarthel          #+#    #+#              #
#    Updated: 2019/01/08 14:12:39 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Set the target
	WWW="slash16.org"

# Set computer name
	CP_NAME=$(networksetup -getcomputername)

# Get the IP address of WWW using public DNS query (nslookup)
#	IP_ADD=$(nslookup slash16.fr 8.8.8.8 | sed -n /'answer'/,//p | grep -e "Address" | grep -o -e "[0-9]*[.][0-9]*[.][0-9]*[.][0-9]*" | head -n 1)

# Get the IP address of WWW using public DNS query (dig)
	IP_ADD=$(dig @8.8.8.8 slash16.fr +short | head -n 1)

# Trace route (identify network interfaces packets are passing through)
	echo "\033[92mNetwork interfaces between $CP_NAME and $WWW: \033[0m"
	traceroute $IP_ADD
