#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    12 IP address assigned by DHCP server              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/08 18:43:18 by abarthel          #+#    #+#              #
#    Updated: 2019/01/08 18:43:18 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Get IP address assigned by DHCP server
	echo "\033[92m$(hostname -s) has been assigned by DHCP server ($(ipconfig getpacket en0 | grep -e "server_identifier" | grep -o -e "[0-9]*[.][0-9]*[.][0-9]*[.][0-9]")) IP: \033[0m"
	hostname | xargs host | grep -o -e "[0-9]*[.][0-9]*[.][0-9]*[.][0-9]"

# Get your public IP address
#	echo "\033[92m$(hostname -s) public IP address:\033[0m"
#	host myip.opendns.com resolver1.opendns.com | grep "has address" | grep -o -e "[0-9]*[.][0-9]*[.][0-9]*[.][0-9]*"
