#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    02 Set a new hostname                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/09 16:33:49 by abarthel          #+#    #+#              #
#    Updated: 2019/01/09 16:33:49 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Get previous hostname
	PHNAME=$(hostname)

# Set hostname (sysitem) name variable
	HNAME="Antoine"

# Change hostname (temp)
	echo "\033[92mTemporarily changed $PHNAME to $HNAME\033[0m"
	hostname $HNAME

# Change hostname (hostnamectl) (perm)
#	echo "\033[92mPermanently changed $PHNAME to $HNAME\033[0m"
#	hostnamectl set-hostname $HNAME
