#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    02 Set a new hostname                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/09 16:33:49 by abarthel          #+#    #+#              #
#    Updated: 2019/01/09 16:33:49 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Get previous hostname
	PHNAME=$(hostname)

# Set hostname (sysitem) name variable
	HNAME="Antoine"

# Change hostname (temp)
	hostname $HNAME

# Change hostname (hostnamectl) (perm)
#	hostnamectl set-hostname $HNAME

# Change hostname in /etc/hosts ()
	sed -i.bak /$WWW/d $HC_PATH && rm *.bak

