#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    02 Set a new hostname                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/09 16:33:49 by abarthel          #+#    #+#              #
#    Updated: 2019/01/09 16:33:49 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Log as root
#	su

# Get previous hostname
	PHNAME=$(hostname)

# Set hostname (sysitem) name variable
	HNAME="Antoine"

# Change hostname (temp)
	hostname $HNAME 2> bin
	if [[ $bin != "" ]]; then
		echo -e "\033[92mTemporarily changed $PHNAME to $HNAME\033[0m"
	else
		echo -e "\033[31mCannot changed $PHNAME to $HNAME\033[0m"
	fi
	rm -f bin

# Change hostname (hostnamectl) (perm)
#	hostnamectl set-hostname $HNAME 2> bin
#	if [[ $bin != "" ]]; then
#		echo -e "\033[92mTemporarily changed $PHNAME to $HNAME\033[0m"
#	else
#		echo -e "\033[31mCannot changed $PHNAME to $HNAME\033[0m"
#	fi
#	rm -f bin
