#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    04 Machine uptime                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/09 17:35:08 by abarthel          #+#    #+#              #
#    Updated: 2019/01/09 17:35:08 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Get machine uptime:
	if ! TIME=$(uptime 2>/dev/null); then
		echo "\033[31mCould not tell uptime\033[0m"
		exit
	fi

	if [[ $TIME == *"day"* ]]; then
		echo "\033[92mMachine running for (ddd hh:mm):\033[0m"
		echo $TIME | cut -d " " -f3,4,5 | sed 's/,//g'
	else
		echo "\033[92mMachine running for (hh:mm):\033[0m"
		echo $TIME | cut -d " " -f3 | sed 's/,$//'
	fi
