#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    04 Machine uptime                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/09 17:35:08 by abarthel          #+#    #+#              #
#    Updated: 2019/01/09 17:35:08 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Get machine uptime:
	if [[ $(uname) != "Linux" ]]; then
		echo "\033[92mMachine running for (hh:mm):\033[0m"
		uptime | xargs echo | cut -d " " -f3 | sed 's/,$//'
	else
		echo "\033[92mMachine running for:\033[0m"
		uptime | xargs echo | cut -d " " -f3,4 | sed 's/,$//'
	fi
