#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    05 SSH service status                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/10 14:56:48 by abarthel          #+#    #+#              #
#    Updated: 2019/01/10 14:56:48 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Log as root
#	su

# Get full SSH service status 
#	service ssh status 2> dd
#	if [[ $dd != "" ]]; then
#		echo -e "\033[92mSSH service status: \033[0m$SSH_STATUS"
#	else
#		echo -e "\033[31mSSH service status unknown\033[0m"
#	fi
#	rm -f dd

# Get SSH service status (run, stop, etc.)
	service ssh status 2> dd | grep -i "Active" | xargs echo | cut -c 9-
	if [[ $dd != "" ]]; then
		echo -e "\033[92mSSH service status: \033[0m$SSH_STATUS"
	else
		echo -e "\033[31mSSH service status unknown\033[0m"
	fi
	rm -f dd
