#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    05 SSH service status                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/10 14:56:48 by abarthel          #+#    #+#              #
#    Updated: 2019/01/10 14:56:48 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Log as root
#	su

# Get full SSH service status 
#	if ! SSH_STATUS=$(systemctlstatus ssh 2>/dev/null); then
#		echo "\033[31mCould not tell SSH service status\033[0m"
#		exit
#	else
#		$SSH_STATUS | grep -i Active | xargs echo | cut -c 9-
#	fi

# Get SSH service status (run, stop, etc.)
	if ! SSH_STATUS=$(service ssh status 2>/dev/null); then
		echo "\033[31mCould not tell SSH service status\033[0m"
		exit
	else
		echo $SSH_STATUS | awk -v FS="(Active|Process)" '{print $2}' 2>/dev/null
	fi
