#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    06 Restart SSH service                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/10 14:56:48 by abarthel          #+#    #+#              #
#    Updated: 2019/01/10 14:56:48 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Log as root
#	su

# Restart SSH service (using /etc/init.d/ssh)
#	/etc/init.d/ssh restart

# Restart SSH service (service)
#	service ssh restart

# Restart SSH service (systemctl)
	systemctl restart ssh
