#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    07 SSH service PID                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/10 15:11:17 by abarthel          #+#    #+#              #
#    Updated: 2019/01/10 15:11:17 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Get SSH service Process ID
#	cat /var/run/sshd.pid > bin2
#	if [[ $bin2 == "" ]]; then
#		echo -e "\033[31mNo SSH service has been found\033[0m"
#	else
#		echo -e "\033[92mSSH service PID:\033[0m"
#		echo -e $bin2
#	fi
#	rm -f bin2

# Get SSH service Process ID (ps aux)
	ps aux | grep shh | grep -v grep | grep sbin | awk '{print $2}' > bin2
	if [[ $bin2 == "" ]]; then
		echo -e "\033[31mNo SSH service has been found\033[0m"
	else
		echo -e "\033[92mSSH service PID:\033[0m"
		echo -e $bin2
	fi
	rm -f bin2
