#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    09 List of accessible users                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/10 17:42:47 by abarthel          #+#    #+#              #
#    Updated: 2019/01/10 17:42:47 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Lists information about accessible users
	who
