#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    13 List of ongoing processes                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/10 18:02:40 by abarthel          #+#    #+#              #
#    Updated: 2019/01/10 18:02:40 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Lists processes
	top

# List launched processes
#	ps
