#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    15 Kill a process                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/10 18:14:09 by abarthel          #+#    #+#              #
#    Updated: 2019/01/10 18:14:09 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Kill the tail process (kill)
	ps | grep "tail" | grep -v "grep" | awk '{print $1}' | xargs kill
