#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    17 Log into a remote machine using SSH             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/11 15:59:37 by abarthel          #+#    #+#              #
#    Updated: 2019/01/11 15:59:37 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Set IP address of the target
	IP_TARGET="10.12.1.134"

# Set the user name of the target
	USER_TARGET="username"
	# User password: "root"

# Log into the remote machine and login
	ssh $USER_TARGET@$IP_TARGET
