#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    18 End SSH session                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/11 17:08:38 by abarthel          #+#    #+#              #
#    Updated: 2019/01/11 18:49:39 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# End SSH session on the remotely connected user session
#	exit

# Logout SSH session on the remotely connected user session
#	logout

# Kill SSH service from the hosting user system
#	ps aux | grep ssh | grep -v grep | grep pts | awk '{print $2}'

# Stop the SSH service (service)
#	if service ssh stop 2>/dev/null; then
#		echo "\033[92mSSH service successfully stopped\033[0m"
#	else
#		echo "\033[31mSSH service had trouble stopping\033[0m"
#	fi

# Stop the SSH service (systemctl)
	if systemctl stop ssh 2>/dev/null; then
		echo "\033[92mSSH service successfully stopped\033[0m"
	else
		echo "\033[31mSSH service had trouble stopping\033[0m"
	fi
