#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    24 List installed packages                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/14 13:38:21 by abarthel          #+#    #+#              #
#    Updated: 2019/01/14 13:38:21 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Get root privileges
#	su

# Run apt command
	apt list --installed
