#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    01 Print login, UID, home dir path                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/10 13:22:54 by abarthel          #+#    #+#              #
#    Updated: 2019/01/10 13:22:54 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Set passwd path
	PW_PATH="/etc/passwd"

# Get login name, user ID, home directory full path
	cat $PW_PATH | cut -d ':' -f1,3,6 | sed "s/:/ /g" | grep -v -e "#" |
	awk 'BEGIN { print "\033[92mLogin name                User ID      Home directory full path\033[0m"
	             print " --------                  -----        ----------------------" }
			   { printf "\033[36m%-25s \033[33m%5s            \033[37m%1s\n\033[0m", $1, $2, $3 }' | less
