#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    02 Delete user of an ongoing session               :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/14 13:48:16 by abarthel          #+#    #+#              #
#    Updated: 2019/01/14 13:48:16 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #




# Kill the ongoing session
	pkill -KILL -u $USERNAME

# Delete the user
	deluser $USERNAME
