#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    03 Password generator                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/15 11:49:06 by abarthel          #+#    #+#              #
#    Updated: 2019/01/15 11:49:06 by abarthel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

usage () {
echo "usage: ./03 \033[4m[-bdhcnlasSo]\033[0m \033[4m[size]\033[0m [characters]\n--help to display help page"
exit
}

help_op (){
echo "PASSWORD GENERATOR by abarthel\nversion 0.1\nlast update 2019-01-15\n"
	
echo "usage: ./03 \033[4mtype\033[0m \033[4msize\033[0m [characters]
 options:
   --help, to display help page
   types:
   -b\tbinary
   -d\tdecimal
   -h\thexadecimal
   -c\tcapital letters
   -n\tupper case alphanumerical
   -l\tlower case alphanumerical
   -a\tlower and upper case alphanumerical
   -s\talphanumerical(upper lower 0-9) with special characters
   -S\talphanumerical(upper lower 0-9) with more special characters
   -o \033[4msize\033[0m \033[4m[A-Za-z0-9!\"#$%&'\''()*+,-./:;<=>?@[]^_\`{|}~]\033[0m
   create a password with own set characters (tr like regex) \033[4m[A-Za-z0-9!\"#$%&'\''()*+,-./:;<=>?@[]^_\`{|}~]\033[0m of size \033[4msize\033[0m
 
 usage example:  
   -b \033[4msize\033[0m, binary type password of size \033[4msize\033[0m

Example:
   get binary password of length 18 011001011011110001
    ./03 -b 18
   get alphanumeric password with extra special characters of length 15 \(N\'TMH\|lF\&oM6Xe
    ./03 -S 15
   get hexadecimal password of length 4 96E7
    ./03 -h 4"
exit
}

type_selector () {
	case "$1" in
		"--help")
			help_op
			;;
		"-b") #binary code 0 and 1    2s
			type='0-1'
			;;
		"-d") #decimal 0 to 9     10s
			type='0-9'
			;;
		"-h") #hexaecimal 0-9 and A-F   16s
			type='A-F0-9'
			;;
		"-c") #capital letter alphabet A-Z   26s
			type='A-Z'
			;;
		"-n") #alphanum 0-9 A-Z   36s
			type='0-9A-Z'
			;;
		"-l") # lower case alphabet A-Z a-z  52s
			type='A-Za-z'
			;;
		"-a") #lower and uper alphanumerical A-Z a-z 0-9  62s
			type='A-Za-z0-9'
			;;
		"-s") # alphanumerical(upper lower 0-9) with special characters   70s
			type='A-Za-z0-9!#$*%?'
			;;
		"-S") # alphanumerical(upper lower 0-9) with more special characters    94s
			type='A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~'
			;;
		"-o") # set your own values using regex       Xs
			if test $3; then
				type=$3
			else
				usage
			fi
			;;
		*)
			echo "$0: illegal option --$1"
			usage
			;;
	esac
}

display (){
	echo $1
}

# MAIN
psswd=""
if test $1; then
	if [ $1 = "--help" ]; then
		help_op
	fi
	if test $3; then
		type_selector $1 $2 $3
	elif test $2; then
		type_selector $1 $2
	else
		usage
	fi
else
	usage
fi
while [ ${#psswd} -lt $2 ]
do
	psswd="$psswd$(dd if=/dev/urandom bs=1 count=1 2>/dev/null | tr -dc $type 2>/dev/null)"
done
display $psswd
